version: '3.9'
services:
  db:
    image: postgres
    container_name: db
    env_file:
      - .db.env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
