CREATE TABLE shortener(
  id VARCHAR(36) PRIMARY KEY,
  longurl TEXT NOT NULL,
  shorturl CHAR(6) NOT NULL UNIQUE,
  expiresin TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
